#!/usr/bin/env bash
#==============================================================================
# regenerate_screenshots.sh — rebuild all documentation screenshots from the
# current source. Produces the full set used by docs/MANUAL.md and marketing.
#
# Usage:
#   bash scripts/regenerate_screenshots.sh
#
# Output directory: docs/assets/
#==============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT_DIR="docs/assets"
TOOL="./build/screenshot_tool"
SCALE="2.0"

mkdir -p "$OUT_DIR"

# --- Ensure screenshot_tool is built ----------------------------------------
if [ ! -x "$TOOL" ]; then
    echo "Building screenshot_tool..."
    if [ ! -d build ]; then
        cmake -B build -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev >/dev/null
    fi
    # screenshot_tool depends on JuceHeader.h generated by the plugin target
    cmake --build build --target OpenSpatialDelay_VST3 -j"$(sysctl -n hw.ncpu)" \
        >/dev/null
    cmake --build build --target screenshot_tool -j"$(sysctl -n hw.ncpu)"
fi

mkdir -p "$OUT_DIR/presets"

# Presets chosen per screenshot for visual clarity:
MAIN_PRESET="Quad Ping-Pong"          # 4 taps at cardinal positions — baseline preset
PRESET_MENU_PRESET="Merry-Go-Round"   # nested submenu demo — Spatial Movement category (issue #168 r2)

echo ""
echo "=== Regenerating screenshots ==="

# --- Full editor screenshot: hero state (issue #168 r3, item 7) -------------
# Hero mode renders the "features-on" showcase state + Global Drawer open +
# populated undo history + per-tap activity glow + custom preset label
# ("Infinity Halo") + an Infinity trajectory drawn on the spatial map.
# Tap 1 is L-only, +7 st pitch, 75% Doppler; taps 3/6/9 disabled, 10/11/12
# enabled and redistributed. --showcase is implicit in this mode.
# This image is the PIL-crop source for header / right-panel / bottom-panel.
"$TOOL" "$OUT_DIR/screenshot.png"         "$SCALE" --preset "$MAIN_PRESET"      --mode hero
cp "$OUT_DIR/screenshot.png" "$OUT_DIR/screenshot_full.png"

# --- Direct-snapshot captures (no PIL crop required) -----------------------
"$TOOL" "$OUT_DIR/screenshot_spatial_map.png"   "$SCALE" --preset "$MAIN_PRESET"      --mode spatial-map
"$TOOL" "$OUT_DIR/screenshot_elevation_map.png" "$SCALE" --preset "$MAIN_PRESET"      --mode elevation-map
"$TOOL" "$OUT_DIR/screenshot_drawer.png"        "$SCALE" --preset "$MAIN_PRESET"      --mode drawer-open
# TONE crop uses showcase state so the filter graph is on with asymmetric Q.
"$TOOL" "$OUT_DIR/screenshot_tone_section.png"  "$SCALE" --preset "$MAIN_PRESET"      --mode tone-section --showcase
"$TOOL" "$OUT_DIR/screenshot_osc_section.png"   "$SCALE" --preset "$MAIN_PRESET"      --mode osc-section
"$TOOL" "$OUT_DIR/screenshot_save_preset.png"   "$SCALE" --preset "$MAIN_PRESET"      --mode save-overlay
# Preset menu: Merry-Go-Round lives in "Spatial Movement" — the submenu ticks it.
"$TOOL" "$OUT_DIR/screenshot_preset_menu.png"   "$SCALE" --preset "$PRESET_MENU_PRESET" --mode preset-menu
# NOTE (issue #168 round 3, item 10): screenshot_output_menu.png is HITL —
# the generated mock failed to match the real JUCE ComboBox popup after
# multiple iterations. The file is now a live-plugin capture committed
# directly. Do NOT regenerate it from --mode output-dropdown; the mock is
# retained in the tool for future reference only. See
# docs/SCREENSHOT_REVIEW_ROUND_3.md § "Item 10 — HITL" for details.
# "$TOOL" "$OUT_DIR/screenshot_output_menu.png"   "$SCALE" --preset "$MAIN_PRESET"      --mode output-dropdown
"$TOOL" "$OUT_DIR/screenshot_undo_active.png"   "$SCALE" --preset "$MAIN_PRESET"      --mode undo-active
# Annotated source (issue #168 r3): showcase state + Global Drawer open + undo
# history populated. annotate_screenshot.py reads this as its SRC.
"$TOOL" "$OUT_DIR/screenshot_annotated_source.png" "$SCALE" --preset "$MAIN_PRESET"    --mode annotated-source

# --- Per-preset showcase captures (preset-showcase mode) --------------------
# One screenshot per preset, each with a distinct output-format / algorithm
# (or stereo-mode / HRTF-profile) combination so the full set reads as a
# slideshow of what the plugin can do. preset-showcase mode pumps the
# processor so trajectory.tick() advances — any animated shape's trail is
# visible in the still frame via setDrawFullTrajectoryForScreenshot.
"$TOOL" "$OUT_DIR/presets/merry-go-round.png"    "$SCALE" --preset "Merry-Go-Round"    --mode preset-showcase --output-format "9.1.4 Atmos"    --surround-algo "VBAP"
"$TOOL" "$OUT_DIR/presets/multi-tap-cascade.png" "$SCALE" --preset "Multi-Tap Cascade" --mode preset-showcase --output-format "7.1 Surround"   --surround-algo "Constant Power"
"$TOOL" "$OUT_DIR/presets/spiral-descent.png"    "$SCALE" --preset "Spiral Descent"    --mode preset-showcase --output-format "7.1.4 Atmos"    --surround-algo "MDAP"
"$TOOL" "$OUT_DIR/presets/random-walk.png"       "$SCALE" --preset "Random Walk"       --mode preset-showcase --output-format "5.1.2 Atmos"    --surround-algo "KNN"
"$TOOL" "$OUT_DIR/presets/kaleidoscope.png"      "$SCALE" --preset "Kaleidoscope"      --mode preset-showcase --output-format "Octaphonic"     --surround-algo "VBIP"
"$TOOL" "$OUT_DIR/presets/frozen-cascade.png"    "$SCALE" --preset "Frozen Cascade"    --mode preset-showcase --output-format "9.1.6 Atmos"    --surround-algo "DBAP"
"$TOOL" "$OUT_DIR/presets/grain-cloud.png"       "$SCALE" --preset "Grain Cloud"       --mode preset-showcase --output-format "4th Order Ambi"
"$TOOL" "$OUT_DIR/presets/dome-ring.png"         "$SCALE" --preset "Dome Ring"         --mode preset-showcase --output-format "SpatialMediaLab 13.1" --surround-algo "MDAP"
"$TOOL" "$OUT_DIR/presets/atmos-7-1-4.png"       "$SCALE" --preset "Atmos 7.1.4"       --mode preset-showcase --output-format "7.1.4 Atmos"    --surround-algo "Constant Power"
"$TOOL" "$OUT_DIR/presets/micro-delay.png"       "$SCALE" --preset "Micro Delay"       --mode preset-showcase --output-format "Binaural"       --hrtf-profile "Studio Reference"
"$TOOL" "$OUT_DIR/presets/offbeat-pong.png"      "$SCALE" --preset "Offbeat Pong"      --mode preset-showcase --output-format "Stereo"         --stereo-mode "XY Pair"
"$TOOL" "$OUT_DIR/presets/west-african-bell.png" "$SCALE" --preset "West African Bell" --mode preset-showcase --output-format "Quadraphonic"   --surround-algo "VBAP"
"$TOOL" "$OUT_DIR/presets/cinquillo.png"         "$SCALE" --preset "Cinquillo"         --mode preset-showcase --output-format "5.0 Surround"   --surround-algo "KNN"
"$TOOL" "$OUT_DIR/presets/shimmer.png"           "$SCALE" --preset "Shimmer"           --mode preset-showcase --output-format "2nd Order Ambi"
"$TOOL" "$OUT_DIR/presets/hemisphere-spread.png" "$SCALE" --preset "Hemisphere Spread" --mode preset-showcase --output-format "7.1.2 Atmos"    --surround-algo "VBIP"
"$TOOL" "$OUT_DIR/presets/tape-wow.png"          "$SCALE" --preset "Tape Wow"          --mode preset-showcase --output-format "Binaural"       --hrtf-profile "Immersive"

# --- Per-trajectory reference captures (issue #168 follow-up) ---------------
# SpatialMap only, one tap enabled at (az=0, el=0, dist=0.5), trajectory
# drawn at full brightness. Each shape uses a different tap (so colour
# varies); Triangle wraps back to Tap 4 since there are 13 shapes and 12 taps.
mkdir -p "$OUT_DIR/trajectories"
"$TOOL" "$OUT_DIR/trajectories/traj_bounce.png"   "$SCALE" --mode trajectory --trajectory Bounce   --tap 1
"$TOOL" "$OUT_DIR/trajectories/traj_circle.png"   "$SCALE" --mode trajectory --trajectory Circle   --tap 2
"$TOOL" "$OUT_DIR/trajectories/traj_cross.png"    "$SCALE" --mode trajectory --trajectory Cross    --tap 3
"$TOOL" "$OUT_DIR/trajectories/traj_figure8.png"  "$SCALE" --mode trajectory --trajectory Figure-8 --tap 4
"$TOOL" "$OUT_DIR/trajectories/traj_heart.png"    "$SCALE" --mode trajectory --trajectory Heart    --tap 5
"$TOOL" "$OUT_DIR/trajectories/traj_helix.png"    "$SCALE" --mode trajectory --trajectory Helix    --tap 6
"$TOOL" "$OUT_DIR/trajectories/traj_infinity.png" "$SCALE" --mode trajectory --trajectory Infinity --tap 7
"$TOOL" "$OUT_DIR/trajectories/traj_line.png"     "$SCALE" --mode trajectory --trajectory Line     --tap 8
"$TOOL" "$OUT_DIR/trajectories/traj_orbit.png"    "$SCALE" --mode trajectory --trajectory Orbit    --tap 9
"$TOOL" "$OUT_DIR/trajectories/traj_random.png"   "$SCALE" --mode trajectory --trajectory Random   --tap 10
"$TOOL" "$OUT_DIR/trajectories/traj_spiral.png"   "$SCALE" --mode trajectory --trajectory Spiral   --tap 11
"$TOOL" "$OUT_DIR/trajectories/traj_square.png"   "$SCALE" --mode trajectory --trajectory Square   --tap 12
"$TOOL" "$OUT_DIR/trajectories/traj_triangle.png" "$SCALE" --mode trajectory --trajectory Triangle --tap 4

# --- PIL crops derived from the full editor screenshot ----------------------
# Native plugin dimensions: 820 x 580. At scale=2, image is 1640 x 1160.
# Layout constants (scaled):
#   Header            y   0 –  104  (top 52 native)
#   Right panel X     x 1112 – 1640 (width 264 native)
#   OSC header Y      y ≈ 1028       (rpBottom - 60 native = 514 native — rightPanel
#                                    is reduced by 6px vertical padding, so rpBottom
#                                    lands at 574 native, not the window bottom)
#   Bottom panel Y    y  920 – 1160 (height 120 native)
python3 - <<'PY'
from PIL import Image
from pathlib import Path

OUT_DIR = Path("docs/assets")
full = Image.open(OUT_DIR / "screenshot.png")

crops = {
    # Top header strip — full width, SML + preset row + format dropdowns.
    # Crop ends at the header/map divider (issue #168 round 3, item 17).
    "screenshot_header.png":       (full, (0,    0,   1640, 104 )),
    # Right panel — DELAY + MOD + TONE + MIX (stops 10px above OSC section header)
    "screenshot_right_panel.png":  (full, (1112, 104, 1640, 1018)),
    # Bottom panel — per-tap row only (tap selector + per-tap controls)
    # Stops at right-panel edge so MIX / OSC don't bleed in.
    "screenshot_bottom_panel.png": (full, (0,    920, 1112, 1160)),
}

for fname, (src, box) in crops.items():
    src.crop(box).save(OUT_DIR / fname)
    print(f"  crop → {fname} ({box[2]-box[0]}x{box[3]-box[1]})")
PY

# --- Regenerate annotated screenshot ----------------------------------------
python3 docs/assets/annotate_screenshot.py

echo ""
echo "=== Done ==="
ls -la "$OUT_DIR"/screenshot*.png
