#!/usr/bin/env bash
#==============================================================================
# regenerate_screenshots.sh — rebuild all documentation screenshots from the
# current source. Produces the full set used by docs/MANUAL.md and marketing.
#
# Usage:
#   bash scripts/regenerate_screenshots.sh
#
# Output directory: docs/assets/
#==============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT_DIR="docs/assets"
TOOL="./build/screenshot_tool"
SCALE="2.0"

mkdir -p "$OUT_DIR"

# --- Ensure screenshot_tool is built ----------------------------------------
if [ ! -x "$TOOL" ]; then
    echo "Building screenshot_tool..."
    if [ ! -d build ]; then
        cmake -B build -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev >/dev/null
    fi
    # screenshot_tool depends on JuceHeader.h generated by the plugin target
    cmake --build build --target OpenSpatialDelay_VST3 -j"$(sysctl -n hw.ncpu)" \
        >/dev/null
    cmake --build build --target screenshot_tool -j"$(sysctl -n hw.ncpu)"
fi

# Presets chosen per screenshot for visual clarity:
MAIN_PRESET="Quad Ping-Pong"      # 4 taps at cardinal positions — clean reference
ELEVATION_PRESET="Rising Spiral"  # shows varied elevations in the dome view

echo ""
echo "=== Regenerating screenshots ==="

# --- Full editor screenshot (used as source for header/panel/map crops) -----
"$TOOL" "$OUT_DIR/screenshot.png"         "$SCALE" --preset "$MAIN_PRESET"      --mode full
cp "$OUT_DIR/screenshot.png" "$OUT_DIR/screenshot_full.png"

# --- Elevation-focused full editor (source for elevation_map crop) ----------
"$TOOL" "$OUT_DIR/_tmp_elevation.png"      "$SCALE" --preset "$ELEVATION_PRESET" --mode full

# --- New captures -----------------------------------------------------------
"$TOOL" "$OUT_DIR/screenshot_drawer.png"       "$SCALE" --preset "$MAIN_PRESET"      --mode drawer-open
"$TOOL" "$OUT_DIR/screenshot_tone_section.png" "$SCALE" --preset "$MAIN_PRESET"      --mode tone-section
"$TOOL" "$OUT_DIR/screenshot_osc_section.png"  "$SCALE" --preset "$MAIN_PRESET"      --mode osc-section
"$TOOL" "$OUT_DIR/screenshot_save_preset.png"  "$SCALE" --preset "$MAIN_PRESET"      --mode save-overlay
"$TOOL" "$OUT_DIR/screenshot_preset_menu.png"  "$SCALE" --preset "$MAIN_PRESET"      --mode preset-menu
"$TOOL" "$OUT_DIR/screenshot_output_menu.png"  "$SCALE" --preset "$MAIN_PRESET"      --mode output-dropdown
"$TOOL" "$OUT_DIR/screenshot_undo_active.png"  "$SCALE" --preset "$MAIN_PRESET"      --mode undo-active

# --- Crops derived from the full screenshots (via PIL) ----------------------
# Native plugin dimensions: 820 x 580. At scale=2, image is 1640 x 1160.
# - Header:        y  0 – 104  (native 0 – 52)
# - Spatial map:   x  0 – 1112, y 104 – 860  (native 0 – 556, 52 – 430)
# - Right panel:   x  1112 – 1640, y 104 – 860
# - Bottom panel:  y 860 – 1160
python3 - <<'PY'
from PIL import Image
from pathlib import Path

OUT_DIR = Path("docs/assets")
full = Image.open(OUT_DIR / "screenshot.png")
elev = Image.open(OUT_DIR / "_tmp_elevation.png")

crops = {
    "screenshot_header.png":       (full, (0,    0,   1640, 104 )),
    "screenshot_spatial_map.png":  (full, (0,    104, 1112, 860 )),
    "screenshot_right_panel.png":  (full, (1112, 104, 1640, 860 )),
    "screenshot_bottom_panel.png": (full, (0,    860, 1640, 1160)),
    "screenshot_elevation_map.png":(elev, (0,    104, 1112, 860 )),
}

for fname, (src, box) in crops.items():
    src.crop(box).save(OUT_DIR / fname)
    print(f"  crop → {fname} ({box[2]-box[0]}x{box[3]-box[1]})")

(OUT_DIR / "_tmp_elevation.png").unlink()
PY

# --- Regenerate annotated screenshot ----------------------------------------
python3 docs/assets/annotate_screenshot.py

echo ""
echo "=== Done ==="
ls -la "$OUT_DIR"/screenshot*.png
